### ISSUE TITLE
Why does the view folder is separated from the Modules folder ? 

### ISSUE THREAD

**Issue by afifanshorulhaq** [MufidJamaluddin/Codeigniter4-HMVC#5]
hi i'm just asking why does the view folder get separated from Modules folder i found this kinda strange since i'm just starting to learn the hmvc in code igniter 4, this is not issue sorry to post this question here

**Comment by MufidJamaluddin** [comment]
I stored view folder in separated module because it's compatible with base CodeIgniter4 project structure and easy to upgrade CodeIgniter4.

If you want to store the view folder in modules with models and controllers, you can do it and include your views directly into your controller. It's very flexible to re-arrange the project structure because it's PSR-4.
